import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "#F2F6FD",
          100: "#C2D7F7",
          200: "#92B7F1",
          300: "#6298EB",
          400: "#3278E5",
          500: "#0359E0",
          600: "#0247B3",
          700: "#013586",
          800: "#012359",
          900: "#00112C",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: "#F2FCFD",
          100: "#C2F1F7",
          200: "#92E6F1",
          300: "#62DCEB",
          400: "#32D1E5",
          500: "#03C7E0",
          600: "#029FB3",
          700: "#017786",
          800: "#014F59",
          900: "#00272C",
        },
        tertiary: {
          50: "#FFFCF4",
          100: "#FFF2CA",
          200: "#FFE8A1",
          300: "#FFDE77",
          400: "#FFD44E",
          500: "#FFCA25",
          600: "#CCA11D",
          700: "#997916",
          800: "#66500E",
          900: "#322807",
        },
        dark: {
          50: "#EFEFEF",
          100: "#C8C8C8",
          200: "#9D9D9D",
          300: "#727272",
          400: "#474747",
          500: "#1C1C1C",
          600: "#161616",
          700: "#101010",
          800: "#0B0B0B",
          900: "#050505",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        danger: {
          DEFAULT: "#CB2E27",
          light: "#FCF4F4",
        },
        warning: {
          DEFAULT: "#FFAD0D",
          light: "#FFFAF2",
        },
        success: {
          DEFAULT: "#2A7E2E",
          light: "#F4F8F4",
        },
        info: {
          DEFAULT: "#0C6FBF",
          light: "#F2F7FB",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
